### ISSUE TITLE
K8S_时间同步

### ISSUE THREAD

**Issue by donkeytt11111** [donkeytt11111/jiaxin.github.io#30]
在 Kubernetes 集群中部署 NTP DaemonSet 以同步时间
以下是详细步骤，创建和部署一个 NTP DaemonSet 来同步所有 Pod 的时间。
👍 
步骤 1：创建 ConfigMap
ConfigMap 用于存储 NTP 配置文件。创建一个名为 ntp-config 的 ConfigMap，其中包含 ntp.conf 配置文件。

创建一个名为 ntp-config.yaml 的文件，并添加以下内容：

```yaml
复制代码
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntp-config
data:
  ntp.conf: |
    server 0.pool.ntp.org iburst
    server 1.pool.ntp.org iburst
    server 2.pool.ntp.org iburst
    server 3.pool.ntp.org iburst
```
应用 ConfigMap 到 Kubernetes 集群：

kubectl apply -f ntp-config.yaml

👍 
步骤 2：创建 DaemonSet
创建一个 DaemonSet 来确保每个节点上都运行一个 NTP 容器。

创建一个名为 ntp-daemonset.yaml 的文件，并添加以下内容：

```yaml
复制代码
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ntp-daemonset
spec:
  selector:
    matchLabels:
      name: ntp
  template:
    metadata:
      labels:
        name: ntp
    spec:
      containers:
      - name: ntp
        image: cturra/ntp
        securityContext:
          capabilities:
            add:
            - SYS_TIME
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
        - name: host-etc
          mountPath: /etc/ntp.conf
          subPath: ntp.conf
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: host-etc
        configMap:
          name: ntp-config
```
应用 DaemonSet 到 Kubernetes 集群：

kubectl apply -f ntp-daemonset.yaml

👍 
步骤 3：验证 DaemonSet
确保 DaemonSet 已经成功部署，并且 NTP 容器正在所有节点上运行。

查看 DaemonSet 的状态：

kubectl get daemonset ntp-daemonset
输出应类似如下：

NAME           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
ntp-daemonset  3         3         3       3            3           <none>          10m

查看运行中的 Pod：

kubectl get pods -l name=ntp -o wide
确认每个节点上都有一个运行中的 NTP Pod。

进入一个 NTP Pod 并检查 NTP 状态：

kubectl exec -it <ntp-pod-name> -- ntpq -p
确认 NTP 服务器已经同步。

通过这些步骤，你将部署一个 NTP DaemonSet 来同步所有节点上的时间，这将确保所有 Pod 的时间与主机时间一致。
