### ISSUE TITLE
集群时间同步注入器.yaml

### ISSUE THREAD

**Issue by donkeytt11111** [donkeytt11111/jiaxin.github.io#35]
```yaml
---
# Source: k8tz/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: k8tz
  labels:
    k8tz.io/controller-namespace: "true"
    helm.sh/chart: k8tz-0.16.1
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: k8tz/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8tz
  namespace: k8tz
  labels:
    helm.sh/chart: k8tz-0.16.1
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: k8tz/templates/admission-webhook.yaml
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lRVmVxclBqazRQYmQ2TndYdDJRRE5pVEFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFERXcxck9IUjZMbXM0ZEhvdWMzWmpNQjRYRFRJME1EWXdOREExTVRBMU5Gb1hEVE00TURZdwpOVEExTVRBMU5Gb3dHREVXTUJRR0ExVUVBeE1OYXpoMGVpNXJPSFI2TG5OMll6Q0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOZmhNSU11ZGZDdzdjcFpWdW9pZ1Z3VGNUQjZzWFVrT1RJSHdUUU8KZU9HN1hRMWJoNWFmZ1NVZUhkK3FUdTIvZFFVaWp3VjNkSjJ1THoxY0dhSU1UNGNIbzVTMXF4L3haRFRsbjljUQpxaE82Q1NXMHVTekg4UUh2KzRIU2pJWEhGS0toSEFEZ2ROUkRHdVNrM2wwZDJjeGhVREVPNFY3R2xEZEhKTUg5ClFRVWNibFYvS0ZLcE5GZU1UM1pPM2VjbEVUQ2kvaDlscVhvSDNRbDNkZUNTMkpaLy9sTW9SeTczYlBCY0h2TFEKWmlFTUVRTjdyWnIvNXI1WU1qWVNPdFdGemI2WjR3c05nUW1saStUV2xIUWNNK283UmVQTXNLYS9nZ0xWaDUrYQozcVpHRzFNNGdZZS8zZTRGaXlSZ3ZENStWbDErUzlYMFpNTXc5a3VJbmljZGN0OENBd0VBQWFOWk1GY3dEZ1lEClZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlYKSFJNQkFmOEVBakFBTUJnR0ExVWRFUVFSTUErQ0RXczRkSG91YXpoMGVpNXpkbU13RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFOT2trNnlVdW4vU2d1Ynp2QUZRN25OalVvRXhQYmM3bXNmZDJsZ0JmczFUc04zaFE5S2tJNTRuCmU5TVhNRFI5RkVUUFVwZW5vMDF0ZnNaQXgwODJMMXIya1BlenhNN2QxZ0wvUjhJdHJjRDZoWG5ldzAxVWhDMisKZUJWTDN5endBRld4SXRab0xVR1orcEJlaWxWcDBraDBrVUxJWHF0ZG9meEZrbFYyMSsxdjlFWXZrSjdySm1lVwp5Tm0rWWttbmxocjNSY3cyZWkzQVpKU0VJSktzaHhacmZHaEhNSTBFcmE3SkxzUEJWMm9JMW5nYWR3amltdEMzCjdPWGRtcW1KYlBZemRxdi9TUXFCOTVwS1kvWUhtVjZ5d1YvM0toUmI1ZXZMT05hczZ6ZFk0MTg2NkpsdGoxR0IKU2ZyQmRmekJ4VnBrSTM4QnBncTJNQUNBU2VaNlRmND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMStFd2d5NTE4TER0eWxsVzZpS0JYQk54TUhxeGRTUTVNZ2ZCTkE1NDRidGREVnVICmxwK0JKUjRkMzZwTzdiOTFCU0tQQlhkMG5hNHZQVndab2d4UGh3ZWpsTFdySC9Ga05PV2YxeENxRTdvSkpiUzUKTE1meEFlLzdnZEtNaGNjVW9xRWNBT0IwMUVNYTVLVGVYUjNaekdGUU1RN2hYc2FVTjBja3dmMUJCUnh1Vlg4bwpVcWswVjR4UGRrN2Q1eVVSTUtMK0gyV3BlZ2ZkQ1hkMTRKTFlsbi8rVXloSEx2ZHM4RndlOHRCbUlRd1JBM3V0Cm12L212bGd5TmhJNjFZWE52cG5qQ3cyQkNhV0w1TmFVZEJ3ejZqdEY0OHl3cHIrQ0F0V0huNXJlcGtZYlV6aUIKaDcvZDdnV0xKR0M4UG41V1hYNUwxZlJrd3pEMlM0aWVKeDF5M3dJREFRQUJBb0lCQVFDUW42TkJidUhDVXJXcgpSdmpNT0R1VGRNN3luRy9BTzNrNXhDb3g5clFTL2RPVC9FcTBwTHovSWRML29YZnBITWVIbmlSVWxEZUMzMHQwCmZ2d0pMTmdtYlA2d3hKZ1UrVUdaa20vbnc1azlSL2VTMUNUdUZEQ29qSjVnMWE0Z2ZVT2N3L1Fmdmo5bWFHSmUKNVBpM1J5VS9INzU2Ynk2YXNNeGd6LytYR2xQeDJHT0ZSamUvMjBMcVltN1k2UEo0SXJZblhnTEx2cGRRMk16SAozUUl0VjhSOU1SU1hDdmZEYmRuTkw0NXk1K2tyK0pPdDhkMXZocVpuY1ZPSitBeVFMSkNtMGZVUmpGYkFBb1EvCm5SdGNRdnI2RmNTS0IvbFh3Y3NxOG02ak4rZE03M2E1a2dRY2FVOWZVM3RvRkU1MFBhV0lsRWQveWZ0Vml1OXcKRnQySkFEVXBBb0dCQU53djcwbmcwQkZ6OVlGTnIvT3lZWUZYL3diaDVoQ0lLK3BMNjdNL3RHMUszY0prTVBUVAozanRacHRQeTdwWEhvREx3M0x5YUZVWXI0VXVzMm5uOVE1aThua2d3SzRsRWkxbDlUZUFncElNbk5ZUWhGOE9FCkNFSHhPVDRwd2dOb3dVQVNtZUo1ZCtqMVBpUDk3M3M0UjNRUW11RkZEVkNOMnRaZFc5UTRrOGZqQW9HQkFQcjkKNVpOR0pBS3pDNzd6Tk0zbHNSZ2E1b0Z1VVRVZEU0QUltMCtKNE4vMnJSTWxnUDVBSUtUaTJ5QUpKU1F0MGdCVQowSDZ6WU9Bc2MydHZYMVJZTDF0eEl4anN6RnQyWVNsbEp5bGRiaXJkRk9uS1BMTVFEUHlDV0U3MGVJWHhZZFBBCi9FemkxV090UzJ0QjhTWWJNdUVxK01xYXNKRDcyV3FUWk5lWmtzSFZBb0dBU2lWbUtmV25lMGtXTWkyc0E1OWQKRUVaR25kV3lPSHp5ZE5xT0MzVjNWNXB2Wk1lQ2FOOXpwWDdDRy90aGRsU2IwS3VsV1dsMW9vU2lRRzU3djdxVwphYmVTZ1hLZkpvRkxmNTRmZkVyaHV6eVgyOStjOWZ6Zkh2MlJMaXEzcDVnK0EwcUFRWEJ2L2FXZ0FGVEJzVGU1CmNBOHJhSkp0TW1RaWZpOC8vZzN6VGNzQ2dZRUE4TitmWmtKbkpzd0wxcnB6RDdLQ3paNXJYd1d2RzZrRzROWGgKcjJpa0Rtd2UxNFFqa2wyYXRvTWNSbGRnZEtNZ3FiNjd4UXlEU1VCL21EaHZKWFBvSnZxaDh6YTJQSVNVWkhTMgpLNldGcDg4NlZkQUhodFU5a1V2S1VpT2VVdlUvckVmR0drZUxBTGo3NnppQ3BNNXZldGFSbzJiblVvelFyODQ2CmRncmxZKzBDZ1lFQWg1bzJIaDRTZ2w3VjVsR3JreUtyeGVMRXk0dStQOHQ0MmFveHVBWnU3Z2dKWGJHRno3ZFMKYmxYcGRYQ21tRzNnaW1iVzNkSzgrNElJRXdJOWdrWnJKVnRvdGllaWdpWW15cityaTM1cjlQRVJSRHljNGUrVwpsMWoycnR4c2w5WjY0cXBVRTAvNllneUoyWnFlVE83UGRUSHVqQW0zSERvYmJZVTNpWStuY1VvPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
kind: Secret
metadata:
  namespace: k8tz
  creationTimestamp: null
  name: k8tz-tls
  labels:
    helm.sh/chart: k8tz-0.16.1
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: k8tz/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8tz-role
  labels:
    helm.sh/chart: k8tz-0.16.1
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
# Source: k8tz/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8tz-role-binding
  labels:
    helm.sh/chart: k8tz-0.16.1
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: k8tz
    namespace: k8tz
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: k8tz-role
---
# Source: k8tz/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: k8tz
  namespace: k8tz
  labels:
    helm.sh/chart: k8tz-0.16.1
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
---
# Source: k8tz/templates/controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8tz
  namespace: k8tz
  labels:
    helm.sh/chart: k8tz-0.16.1
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8tz
      app.kubernetes.io/instance: k8tz
  template:
    metadata:
      annotations:
        checksum/config: 1b65ca92e0327fa2cf61c6d2fde359f580be30a672adf6df067080e3ce04261b
      labels:
        app.kubernetes.io/name: k8tz
        app.kubernetes.io/instance: k8tz
    spec:
      volumes:
        - name: tls
          secret:
            secretName: k8tz-tls
      serviceAccountName: k8tz
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: k8tz
          args:
            - "webhook"
            - "--timezone"
            - "Asia/Shanghai"
            - "--injection-strategy"
            - "initContainer"
            - "--inject=true"
            - "--container-name=k8tz"
            - "--bootstrap-image"
            - "quay.io/k8tz/k8tz:0.16.1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          image: "quay.io/k8tz/k8tz:0.16.1"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls
              mountPath: /run/secrets/tls
              readOnly: true
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          resources: {}
---
# Source: k8tz/templates/admission-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8tz
  labels:
    helm.sh/chart: k8tz-0.16.1
    app.kubernetes.io/name: k8tz
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: admission-controller.k8tz.io
    namespaceSelector:
      matchExpressions:
        - key: k8tz.io/controller-namespace
          operator: NotIn
          values: ["true"]
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - k8tz
            - kube-system
    sideEffects: None
    failurePolicy: Fail
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: k8tz
        namespace: k8tz
        path: "/"
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lRVmVxclBqazRQYmQ2TndYdDJRRE5pVEFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFERXcxck9IUjZMbXM0ZEhvdWMzWmpNQjRYRFRJME1EWXdOREExTVRBMU5Gb1hEVE00TURZdwpOVEExTVRBMU5Gb3dHREVXTUJRR0ExVUVBeE1OYXpoMGVpNXJPSFI2TG5OMll6Q0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOZmhNSU11ZGZDdzdjcFpWdW9pZ1Z3VGNUQjZzWFVrT1RJSHdUUU8KZU9HN1hRMWJoNWFmZ1NVZUhkK3FUdTIvZFFVaWp3VjNkSjJ1THoxY0dhSU1UNGNIbzVTMXF4L3haRFRsbjljUQpxaE82Q1NXMHVTekg4UUh2KzRIU2pJWEhGS0toSEFEZ2ROUkRHdVNrM2wwZDJjeGhVREVPNFY3R2xEZEhKTUg5ClFRVWNibFYvS0ZLcE5GZU1UM1pPM2VjbEVUQ2kvaDlscVhvSDNRbDNkZUNTMkpaLy9sTW9SeTczYlBCY0h2TFEKWmlFTUVRTjdyWnIvNXI1WU1qWVNPdFdGemI2WjR3c05nUW1saStUV2xIUWNNK283UmVQTXNLYS9nZ0xWaDUrYQozcVpHRzFNNGdZZS8zZTRGaXlSZ3ZENStWbDErUzlYMFpNTXc5a3VJbmljZGN0OENBd0VBQWFOWk1GY3dEZ1lEClZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlYKSFJNQkFmOEVBakFBTUJnR0ExVWRFUVFSTUErQ0RXczRkSG91YXpoMGVpNXpkbU13RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFOT2trNnlVdW4vU2d1Ynp2QUZRN25OalVvRXhQYmM3bXNmZDJsZ0JmczFUc04zaFE5S2tJNTRuCmU5TVhNRFI5RkVUUFVwZW5vMDF0ZnNaQXgwODJMMXIya1BlenhNN2QxZ0wvUjhJdHJjRDZoWG5ldzAxVWhDMisKZUJWTDN5endBRld4SXRab0xVR1orcEJlaWxWcDBraDBrVUxJWHF0ZG9meEZrbFYyMSsxdjlFWXZrSjdySm1lVwp5Tm0rWWttbmxocjNSY3cyZWkzQVpKU0VJSktzaHhacmZHaEhNSTBFcmE3SkxzUEJWMm9JMW5nYWR3amltdEMzCjdPWGRtcW1KYlBZemRxdi9TUXFCOTVwS1kvWUhtVjZ5d1YvM0toUmI1ZXZMT05hczZ6ZFk0MTg2NkpsdGoxR0IKU2ZyQmRmekJ4VnBrSTM4QnBncTJNQUNBU2VaNlRmND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: ["CREATE"]
        apiGroups: ["batch"]
        apiVersions: ["v1"]
        resources: ["cronjobs"]
---

```
